name: Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
env:
  OPENRCT2_DIR: OpenRCT2
jobs:
  build:
    name: Build Plugin From Source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: benchwarmer-${{ github.sha }}
          path: build
